### ISSUE TITLE
Artis crashes with artisoptions_classic.h

### ISSUE THREAD

**Issue by AlexHls** [artis-mcrt/artis#20]
#### Issue description
When running an job with `artisoptions.h` set to `artisoptions_classic.h`, the job immediately crashes after start. This does not occur with the `artisoptions_nltenebular.h`. This issue occurred after the latest update (commit 00aa20fa8794f1caba1608cc385fed09c217a685), before that running with `artisoptions_classic.h` did not produce this problem.

#### Steps to reproduce the issue

1.  `cp artisoptions_classic.h artisoptions.h`
2.  `make`
3.  Submit job to local cluster based with adapted version of `artis-virgo-slurmjob.sh` 

#### What's the expected result?

- Job runs and produces `output.txt` files

#### What's the actual result?

- Job crashes with error message 
- [artis_job_8299758.txt](https://github.com/artis-mcrt/artis/files/7553457/artis_job_8299758.txt)

#### Additional details / screenshot

- `input.txt` file of job is attached as well
- [input.txt](https://github.com/artis-mcrt/artis/files/7553459/input.txt)

**Comment by lukeshingles** [comment]
Thanks for the detailed issue report. I believe it should be fixed with the latest commit.

**Comment by AlexHls** [comment]
Thanks for the quick fix! The issue seems to be fixed, at least the job is running as expected now.
